version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reshop
      - POSTGRES_USER=reshop_user
      - POSTGRES_PASSWORD=reshop_secure_password_2024
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: gunicorn --bind 0.0.0.0:8000 --workers 2 --worker-class gevent digital_marketplace.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://reshop_user:reshop_secure_password_2024@db:5432/reshop
      - REDIS_URL=redis://redis:6379/1
      - SECRET_KEY=Jp^Te7f9c!0mk!zZ]P)Q}V3(^Sa`P^I45n}W`+C[9aq.0u#rEZ
      - YOOKASSA_SHOP_ID=test_shop_id_123
      - YOOKASSA_SECRET_KEY=test_secret_key_456
      - ALLOWED_HOSTS=89.185.85.178,localhost,127.0.0.1,0.0.0.0
      - CORS_ALLOWED_ORIGINS=https://89.185.85.178,http://89.185.85.178,http://localhost:3000
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://89.185.85.178:8000/api
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
