# Generated by Django 5.2.3 on 2025-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_comment_order_quantity_order_receipt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='URL изображения товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_info',
            field=models.TextField(blank=True, verbose_name='Информация от продавца'),
        ),
    ]
