# Generated by Django 5.2.3 on 2025-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image_url_product_seller_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, verbose_name='Инструкция по использованию'),
        ),
    ]
