# Generated by Django 5.2.4 on 2025-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_product_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram ID покупателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Username'),
        ),
    ]
