# Generated by Django 5.2.4 on 2025-08-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_telegram_id_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
    ]
