# Generated by Django 5.2.4 on 2025-08-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_avatar_user_bio_user_location_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании оплаты'), ('paid', 'Оплачен'), ('delivered', 'Завершен'), ('payment_rejected', 'Отклонен платежной системой'), ('seller_rejected', 'Отклонен продавцем'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
